---
- assert:
    that:
      - php_version | string | length > 0
      - "'{{ php_version }}' in php_versions"

- name: "{{ php_version }} : install packages"
  apt:
    name:
      - lsphp{{ php_version }}
      - lsphp{{ php_version }}-common
      - lsphp{{ php_version }}-curl
      - lsphp{{ php_version }}-dbg
      - lsphp{{ php_version }}-dev
      - lsphp{{ php_version }}-igbinary
      - lsphp{{ php_version }}-imagick
      - lsphp{{ php_version }}-imap
      - lsphp{{ php_version }}-intl
      - lsphp{{ php_version }}-mysql
      - lsphp{{ php_version }}-opcache
      - lsphp{{ php_version }}-redis
    state: present

- name: "{{ php_version }} : install php7 packages"
  apt:
    name:
      - lsphp{{ php_version }}-json
      - lsphp{{ php_version }}-ioncube
    state: present
  when: php_version == 74

- name: "{{ php_version }} : generate configuration"
  template:
    src: "{{ item.template }}"
    dest: "{{ item.destination }}"
    mode: "0644"
  loop:
    - template: php_ini.j2
      destination: "/usr/local/lsws/lsphp{{ php_version }}/etc/php/{{ php_dot_versions[php_version] }}/mods-available/99-autopilot.ini"
  notify: reload lshttpd
