---
- name: Define redis_package variable.
  set_fact:
    redis_package: "{{ __redis_package }}"
  when: redis_package is not defined

- name: Ensure Redis configuration directory exists.
  file:
    path: "{{ redis_conf_path | dirname }}"
    state: directory
    mode: 0755

- name: Generate Redis configuration.
  template:
    src: redis.conf.j2
    dest: "{{ redis_conf_path }}"
    mode: "{{ redis_conf_mode }}"
  notify: restart redis

- name: Install Redis.
  apt:
    name: "{{ redis_package }}"
    state: present

- name: Ensure Redis is running and enabled on boot.
  service:
    name: "{{ redis_daemon }}"
    state: started
    enabled: true
