---
- name: Add Nginx repository.
  apt_repository:
    repo: ppa:ondrej/nginx
    state: present
  register: add_repository

- name: Install Nginx.
  apt:
    name:
      - nginx
    state: present
    update_cache: "{{ add_repository.changed }}"
  notify: "reload webserver"

- name: Create directories.
  file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
    mode: "0755"
    owner: "{{ item.user }}"
    group: "{{ item.group }}"
  loop:
    - path: "/etc/nginx/global"
      user: root
      group: root
      state: directory
    - path: "/etc/nginx/locations"
      user: root
      group: root
      state: directory

- name: Generate Nginx configuration.
  template:
    src: "{{ item.template }}"
    dest: "{{ item.destination }}"
    mode: "0644"
  loop:
    - template: nginx.j2
      destination: /etc/nginx/nginx.conf
    - template: sites-available/default.j2
      destination: /etc/nginx/sites-available/default
    - template: logrotate.j2
      destination: /etc/logrotate.d/www-logs
  notify:
    - reload webserver

- name: Ensure Nginx is started and enabled on boot.
  service:
    name: nginx
    state: started
    enabled: true
