---
- package_facts:
    manager: "auto"

- assert:
    that:
      - site_name | length > 0
      - site_backup_repo | length > 0
      - site_backup_tag | length > 0
      - site_backup_password | length > 0
      - "'restic' in ansible_facts.packages"

- set_fact:
    backup_path: "/opt/sitepilot/sites/{{ site_name }}"

- name: "initialize backup respository"
  command: "restic -r {{ site_backup_repo }} init"
  environment:
    AWS_ACCESS_KEY_ID: "{{ site_backup_s3_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ site_backup_s3_secret }}"
    RESTIC_PASSWORD: "{{ site_backup_password }}"
  register: command_result
  failed_when: false
  changed_when: false

- name: "backup site files"
  command: "restic -r {{ site_backup_repo }} --tag {{ site_backup_tag }} --quiet --json backup ./files"
  environment:
    AWS_ACCESS_KEY_ID: "{{ site_backup_s3_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ site_backup_s3_secret }}"
    RESTIC_PASSWORD: "{{ site_backup_password }}"
  args:
    chdir: "{{ backup_path }}"
  changed_when: false
  register: result

- name: "result"
  debug:
    msg: "{{ item | from_json }}"
  loop: "{{ result.stdout_lines }}"
