---
- assert:
    that:
      - "'nginx' not in stack"

- name: Add Litespeed repository key.
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "0x011AA62DEDA1F085"
    keyring: /etc/apt/trusted.gpg.d/litespeed.gpg

- name: Add Litespeed repository.
  apt_repository:
    repo: "deb https://rpms.litespeedtech.com/debian/ jammy main"
    state: present
    mode: "0644"

- include_tasks: lsphp.yml
  tags: php

- include_tasks: litespeed.yml
  tags: webserver
