---
- hosts: "{{ host }}"
  pre_tasks:
    - name: Ensure stack variable is defined.
      fail:
        msg: "Stack variable is missing. Set the stack variable in your resource file."
      when: stack is not defined
      tags: [ variable-check ]
  roles:
    - role: ingress
      tags: ingress
      when: "'ingress' in stack"

    - role: nginx
      tags: nginx
      when: "'nginx' in stack"

    - role: litespeed
      tags: litespeed
      when: "'litespeed' in stack"

    - role: msmtp
      tags: msmtp
      when: "'msmtp' in stack"

    - role: composer
      tags: composer
      when: "'composer' in stack"

    - role: wpcli
      tags: wpcli
      when: "'wpcli' in stack"

    - role: mariadb
      tags: mariadb
      when: "'mariadb' in stack"

    - role: phpmyadmin
      tags: phpmyadmin
      when: "'phpmyadmin' in stack"

    - role: nodejs
      tags: nodejs
      when: "'nodejs' in stack"

    - role: redis
      tags: redis
      when: "'redis' in stack"
