---
- name: "admin : create site-admins group"
  group:
    name: site-admins
    state: present

- name: "admin : create site-users group"
  group:
    name: site-users
    state: present

- name: "admin : create sftp-only group"
  group:
    name: sftp-only
    state: present

- name: "admin : ensure '{{ admin }}' user exists"
  user:
    name: "{{ admin }}"
    password: "{{ admin_password }}"
    groups:
      - sudo
      - site-admins
    shell: /bin/bash
    append: true

- name: "admin add authorized keys"
  authorized_key:
    user: "{{ admin }}"
    state: "present"
    key: "{{ admin_authorized_keys | join('\n') }}"
    exclusive: true
