---
- name: "filesystem : create folders"
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: root
    group: root
  loop:
    - "/opt"
    - "/opt/sitepilot"
    - "/opt/sitepilot/sites"
    - "/opt/sitepilot/services"

- name: "filesystem : setup acl"
  acl:
    path: "{{ item.path }}"
    entity: "{{ item.entity }}"
    etype: "{{ item.etype }}"
    permissions: "{{ item.permissions }}"
    default: "{{ item.default }}"
    state: present
  loop:
    - path: "/opt"
      permissions: x
      entity: site-users
      etype: "group"
      default: false
    - path: "/opt/sitepilot/services"
      permissions: ---
      entity: site-users
      etype: "group"
      default: false
