---
- package_facts:
    manager: "auto"

- assert:
    that:
      - phpmyadmin_version is defined
      - docker_network_name is defined
      - "'openresty' in ansible_facts.packages"
      - "'docker-ce' in ansible_facts.packages"

- name: "start container"
  docker_container:
    name: "phpmyadmin"
    hostname: "phpmyadmin"
    image: "phpmyadmin:{{ phpmyadmin_version }}"
    pull: true
    restart_policy: always
    env:
      PMA_HOST: mariadb
      UPLOAD_LIMIT: 1G
      PMA_ABSOLUTE_URI: "/-/phpmyadmin"
    ports:
      - "8001:80"
    networks:
      - name: "{{ docker_network_name }}"
    purge_networks: true
    networks_cli_compatible: false

- name: "configure openresty"
  template:
    src: nginx.j2
    dest: /usr/local/openresty/nginx/conf/locations/phpmyadmin.conf
    mode: "0644"
  notify: reload openresty
