---
- package_facts:
    manager: "auto"

- assert:
    that:
      - phpmyadmin_version | string | length > 0
      - docker_network_name | length > 0
      - "'{{ phpmyadmin_version }}' in phpmyadmin_versions"
      - "'openlitespeed' in ansible_facts.packages"
      - "'docker-ce' in ansible_facts.packages"

- name: "start container"
  docker_container:
    name: "phpmyadmin"
    hostname: "phpmyadmin"
    image: "phpmyadmin:{{ phpmyadmin_version }}"
    pull: true
    restart_policy: always
    env:
      PMA_HOST: mariadb
      UPLOAD_LIMIT: 1G
      PMA_ABSOLUTE_URI: "/-/phpmyadmin"
    ports:
      - "8001:80"
    networks:
      - name: "{{ docker_network_name }}"
    purge_networks: true
    networks_cli_compatible: false
