---
- name: "{{ php_version }} : add repository"
  apt_repository:
    repo: ppa:phpmyadmin/ppa
    state: present
  register: add_repository

- name: "install packages"
  apt:
    name:
      - phpmyadmin
    state: present
    update_cache: "{{ add_repository.changed }}"

- name: "create temp dir"
  ansible.builtin.file:
    path: /var/lib/phpmyadmin/tmp/
    state: directory
    mode: "0700"
    owner: "{{ user_name }}"
    group: "www-data"

- name: "generate config"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  loop:
    - src: nginx.j2
      dest: /etc/nginx/locations/phpmyadmin.conf
    - src: config.j2
      dest: /etc/phpmyadmin/config.inc.php
  notify: reload nginx
