---
- name: "php{{ item }}-fpm : remove pool config"
  file:
    path: "/etc/php/{{ item }}/fpm/pool.d/{{ site_name }}.conf"
    state: absent
  when: (destroy is defined) or (item|string != php_version|string)
  notify: "reload php{{ item }}-fpm"
