---
- name: "php{{ item }}-fpm : remove pool config"
  file:
    path: "/etc/php/{{ item }}/fpm/pool.d/{{ site_name }}.conf"
    state: absent
  when:
    - (item != php_version) or (action is defined and action == 'destroy')
  notify: "reload php{{ item }}-fpm"
