---
- name: copy global MariaDB configuration
  ansible.builtin.template:
    src: mariadb.cnf.j2
    dest: "{{ mariadb_config_file }}"
    owner: root
    group: root
    mode: 0644
    force: "{{ mariadb_overwrite_global_config_file }}"
  notify: restart mariadb

- name: create datadir if it does not exist
  ansible.builtin.file:
    path: "{{ mariadb_datadir }}"
    state: directory
    owner: mysql
    group: mysql
    mode: 0755

- name: ensure MariaDB is started and enabled on boot
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: "{{ mariadb_enabled_on_startup }}"
