---
- name: include task setup.yml
  import_tasks: setup.yml

- name: include task configure.yml
  import_tasks: configure.yml

- name: include task secure.yml
  import_tasks: secure.yml

- name: include task database.yml
  import_tasks: database.yml
