---
- name: Install MariaDB repository key.
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "0xF1656F24C74CD1D8"
  when: mariadb_use_official_repo

- name: Install MariaDB repository.
  apt_repository:
    repo: deb {{ mariadb_use_official_repo_url }}/{{ mariadb_use_official_repo_version }}/{{ ansible_distribution | lower() }} {{ ansible_distribution_release }} main
    filename: mariadb
    state: present
  when: mariadb_use_official_repo

- name: Install MariaDB.
  apt:
    package:
      - mariadb-server
    state: present
    update_cache: true

- name: Install Python MariaDB driver.
  apt:
    name: python3-pymysql
    state: present
