---
- hosts: "{{ host }}"
  tasks:
    - assert:
        that:
          - database_user is defined
          - database_name is defined

    - name: "destroy database {{ database_name }}"
      mysql_db:
        name: "{{ database_name }}"
        state: "absent"
        config_file: "/root/.my.cnf"
      no_log: true

    - name: "destroy database user {{ database_user }}"
      mysql_user:
        name: "{{ database_user }}"
        state: absent
        host: "%"
        config_file: "/root/.my.cnf"
      no_log: true
