---
- assert:
    that:
      - php_version is defined

- name: "{{ php_version }} : add repository"
  apt_repository:
    repo: ppa:ondrej/php
    state: present

- name: "{{ php_version }} : install packages"
  apt:
    name:
      - php{{ php_version }}-bcmath
      - php{{ php_version }}-cli
      - php{{ php_version }}-common
      - php{{ php_version }}-curl
      - php{{ php_version }}-fpm
      - php{{ php_version }}-gd
      - php{{ php_version }}-igbinary
      - php{{ php_version }}-imagick
      - php{{ php_version }}-mbstring
      - php{{ php_version }}-mysql
      - php{{ php_version }}-opcache
      - php{{ php_version }}-readline
      - php{{ php_version }}-redis
      - php{{ php_version }}-soap
      - php{{ php_version }}-xml
      - php{{ php_version }}-zip
    state: present
    update_cache: true
  notify: "reload php{{ php_version }}-fpm"

- name: "{{ php_version }} : generate configuration"
  template:
    src: "{{ item.template }}"
    dest: "{{ item.destination }}"
    mode: "0644"
  notify: "reload php{{ php_version }}-fpm"
  loop:
    - template: www.j2
      destination: "/etc/php/{{ php_version }}/fpm/pool.d/www.conf"
    - template: php_ini.j2
      destination: "/etc/php/{{ php_version }}/fpm/conf.d/90-sitepilot.ini"

- name: "{{ php_version }} : setup acl"
  acl:
    path: "/etc/php/{{ php_version }}/fpm/pool.d"
    entity: site-users
    etype: group
    permissions: ---
    state: present
