---
- package_facts:
    manager: "auto"

- assert:
    that:
      - mailhog_version is defined
      - docker_network_name is defined
      - "'openresty' in ansible_facts.packages"
      - "'docker-ce' in ansible_facts.packages"

- name: "start container"
  docker_container:
    name: "mailhog"
    hostname: "mailhog"
    image: "mailhog/mailhog:{{ mailhog_version }}"
    pull: true
    restart_policy: always
    ports:
      - "127.0.0.1:8002:8025"
      - "127.0.0.1:1025:1025"
    networks:
      - name: "{{ docker_network_name }}"
    purge_networks: true
    networks_cli_compatible: false

- name: "configure openresty"
  template:
    src: nginx.j2
    dest: /usr/local/openresty/nginx/conf/locations/mailhog.conf
    mode: "0644"
  notify: reload openresty
