---
- name: "add repository"
  apt_repository:
    repo: ppa:ondrej/nginx
    state: present
  register: add_repository

- name: "install packages"
  apt:
    name:
      - nginx
    state: present
    update_cache: "{{ add_repository.changed }}"
  notify: reload nginx

- name: "install python libraries"
  pip:
    name:
      - cryptography
    state: present

- name: "create folders"
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "0755"
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
  loop:
    - path: "/etc/nginx/global"
      user: root
    - path: "/etc/nginx/locations"
      user: root
    - path: "/etc/nginx/sites-enabled"
      user: root
    - path: "/etc/nginx/sites-available"
      user: root

- name: "generate default key"
  openssl_privatekey:
    path: /etc/nginx/sites-available/.default.key

- name: "generate default csr"
  openssl_csr:
    path: /etc/nginx/sites-available/.default.csr
    privatekey_path: /etc/nginx/sites-available/.default.key
    country_name: NL
    organization_name: Sitepilot

- name: "generate default certificate"
  openssl_certificate:
    path: /etc/nginx/sites-available/.default.crt
    privatekey_path: /etc/nginx/sites-available/.default.key
    csr_path: /etc/nginx/sites-available/.default.csr
    provider: selfsigned

- name: "generate configuration"
  template:
    src: "{{ item.template }}"
    dest: "{{ item.destination }}"
    mode: "0644"
  notify:
    - reload nginx
  loop:
    - template: nginx.j2
      destination: /etc/nginx/nginx.conf
    - template: global/https.j2
      destination: /etc/nginx/global/https.conf
    - template: global/fastcgi-cache.j2
      destination: /etc/nginx/global/fastcgi-cache.conf
    - template: global/security.j2
      destination: /etc/nginx/global/security.conf
    - template: global/static-files.j2
      destination: /etc/nginx/global/static-files.conf
    - template: sites-available/default.j2
      destination: /etc/nginx/sites-available/default

- name: "setup acl"
  acl:
    path: "/etc/nginx"
    entity: site-users
    etype: group
    permissions: ---
    state: present
