---
- name: "base : install required packages"
  apt:
    name:
      - python3
      - python3-apt
      - python3-pip
      - curl
      - zip
      - unzip
      - acl
      - cron
      - nano
      - rsyslog
      - restic
      - bubblewrap
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: "base : install python libraries"
  pip:
    name:
      - cryptography
    state: present

- name: "base : enable and start rsyslog"
  service:
    name: rsyslog
    state: started
    enabled: true

- name: "base : set timezone"
  timezone:
    name: "{{ timezone }}"

- name: "base : create base folder"
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
  loop:
    - path: "/opt/sitepilot"
      mode: "0755"
