---
- assert:
    that:
      - platform | length > 0
      - hostname | length > 0

- include: base.yml
  tags: "base"

- include: hostname.yml
  tags: "hostname"

- include: sshd.yml
  tags: "sshd"

- include: firewall.yml
  tags: "firewall"

- include: unattended-upgrades.yml
  tags: "unattended-upgrades"
