---
- assert:
    that:
      - hostname | string | length > 0

- include: base.yml
  tags: "base"

- include: hostname.yml
  tags: "hostname"

- include: sshd.yml
  tags: "sshd"

- include: unattended-upgrades.yml
  tags: "unattended-upgrades"
