---
- assert:
    that:
      - hostname | string | length > 0

- import_tasks: base.yml
  tags: "base"

- import_tasks: hostname.yml
  tags: "hostname"

- import_tasks: sshd.yml
  tags: "sshd"

- import_tasks: unattended-upgrades.yml
  tags: "unattended-upgrades"
