---
- assert:
    that:
      - platform | length > 0
      - hostname | length > 0

- include_tasks: base.yml
  tags: "base"

- include_tasks: hostname.yml
  tags: "hostname"

- include_tasks: sshd.yml
  tags: "sshd"

- include_tasks: firewall.yml
  tags: "firewall"

- include_tasks: unattended-upgrades.yml
  tags: "unattended-upgrades"
