---
- name: "sshd : generate configuration"
  template:
    src: sshd_config.j2
    dest: "/etc/ssh/sshd_config"
    mode: "0644"
  notify:
    - reload sshd

- name: "base : install welcome message"
  template:
    src: welcome.j2
    dest: /etc/update-motd.d/00-sitepilot-welcome
    mode: "0755"

- name: "base : cleanup motd files"
  file:
    path: "/etc/update-motd.d/{{ item }}"
    state: absent
  loop:
    - 10-help-text
    - 50-motd-news
    - 50-landscape-sysinfo
    - 85-fwupd
    - 90-updates-available
    - 91-release-upgrade
    - 95-hwe-eol
    - 97-overlayroot
    - 98-fsck-at-reboot
    - 98-reboot-required
