---
- name: "unattended-upgrades : install packages"
  apt:
    name: unattended-upgrades
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: "unattended-upgrades : generate configuration"
  template:
    src: unattended_upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: "root"
    group: "root"
    mode: "0644"
  notify: restart unattended-upgrades
