---
- package_facts:
    manager: "auto"

- assert:
    that:
      - database_backup_repo is defined
      - database_backup_destroy_id is defined
      - database_backup_password is defined
      - "'restic' in ansible_facts.packages"

- name: "destroy backup"
  command: "restic -r {{ database_backup_repo }} forget {{ database_backup_destroy_id }}"
  environment:
    AWS_ACCESS_KEY_ID: "{{ database_backup_s3_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ database_backup_s3_secret }}"
    RESTIC_PASSWORD: "{{ database_backup_password }}"
  changed_when: false
  register: result

- name: "result"
  debug:
    msg: "{{ result.stdout_lines | last }}"
