---
- name: "check packages"
  package_facts:
    manager: "auto"

- name: "add Docker signing keys"
  apt_key:
    url: "{{ item }}"
    state: present
  loop:
    - https://download.docker.com/linux/ubuntu/gpg
  when: "'docker-ce' not in ansible_facts.packages"

- name: "install Docker repositories"
  apt_repository:
    repo: "{{ item }}"
    mode: "0644"
  loop:
    - "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
  when: "'docker-ce' not in ansible_facts.packages"

- name: "install Docker CE"
  apt:
    name: docker-ce

- name: "install Docker python packages"
  pip:
    name: "{{ item }}"
    state: present
  loop:
    - docker

- name: "enable Docker on startup"
  service:
    name: docker
    state: started
    enabled: true

- name: "create default overlay network"
  docker_network:
    name: "{{ docker_network_name }}"
