---
- name: Create Traefik user.
  user:
    name: traefik
    shell: /sbin/nologin
    create_home: no
    state: present

- name: Ensure config directory exists.
  file:
    path: /etc/traefik
    state: directory
    owner: traefik
    group: traefik
    mode: 0775

- name: Generate Traefik configuration.
  template:
    src: traefik.yml.j2
    dest: /etc/traefik/traefik.yml
    owner: traefik
    group: traefik
    mode: 0644
  notify:
    - restart traefik

- name: Generate systemd configuration.
  template:
    src: traefik.service.j2
    dest: /etc/systemd/system/traefik.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart traefik

- name: Check if Traefik binary exists.
  stat:
    path: /usr/bin/traefik
  register: traefik_bin

- name: Download Traefik binary.
  unarchive:
    src: https://github.com/traefik/traefik/releases/download/v2.9.5/traefik_v2.9.5_linux_amd64.tar.gz
    dest: /usr/bin
    owner: root
    group: root
    remote_src: true
    keep_newer: true
  when: not traefik_bin.stat.exists

- name: Ensure Traefik is started and enabled on boot.
  systemd:
    name: traefik
    state: started
    enabled: true
    daemon_reload: true
