---
- assert:
    that:
      - php_version | string | length > 0
      - "'{{ php_version }}' in php_versions"

- name: "{{ php_version }} : Add repository."
  apt_repository:
    repo: ppa:ondrej/php
    state: present
  register: add_repository

- name: "{{ php_version }} : Install packages."
  apt:
    name:
      - php{{ php_version }}-apcu
      - php{{ php_version }}-bcmath
      - php{{ php_version }}-bz2
      - php{{ php_version }}-cli
      - php{{ php_version }}-common
      - php{{ php_version }}-curl
      - php{{ php_version }}-fpm
      - php{{ php_version }}-gd
      - php{{ php_version }}-igbinary
      - php{{ php_version }}-imagick
      - php{{ php_version }}-imap
      - php{{ php_version }}-intl
      - php{{ php_version }}-mbstring
      - php{{ php_version }}-memcached
      - php{{ php_version }}-msgpack
      - php{{ php_version }}-mysql
      - php{{ php_version }}-odbc
      - php{{ php_version }}-opcache
      - php{{ php_version }}-readline
      - php{{ php_version }}-redis
      - php{{ php_version }}-soap
      - php{{ php_version }}-sqlite3
      - php{{ php_version }}-xml
      - php{{ php_version }}-zip
    state: present
    update_cache: "{{ add_repository.changed }}"
  notify: "reload php{{ php_version }}-fpm"

- name: "{{ php_version }} : Generate configuration."
  template:
    src: "{{ item.template }}"
    dest: "{{ item.destination }}"
    mode: "0644"
  notify: "reload php{{ php_version }}-fpm"
  loop:
    - template: www.j2
      destination: "/etc/php/{{ php_version }}/fpm/pool.d/www.conf"
    - template: php_ini.j2
      destination: "/etc/php/{{ php_version }}/fpm/php.ini"

- name: "{{ php_version }} : Update alternatives."
  alternatives:
    name: php
    path: /usr/bin/php{{ php_version }}
