---
- name: Check if PHP is installed.
  command: "php --version"
  changed_when: false

- name: Install WPCLI.
  get_url:
    url: "https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar"
    dest: "/usr/local/bin/wp"
    mode: "0755"
