---
- hosts: "{{ host }}"
  vars:
    site_backup_s3_key: ""
    site_backup_s3_secret: ""
  tasks:
    - package_facts:
        manager: "auto"

    - assert:
        that:
          - site_name is defined
          - site_backup_repo is defined
          - site_backup_tag is defined
          - site_backup_password is defined
          - "'restic' in ansible_facts.packages"

    - set_fact:
        backup_path: "/opt/sitepilot/sites/{{ site_name }}"

    - name: "initialize backup respository"
      command: "restic -r {{ site_backup_repo }} init"
      environment:
        AWS_ACCESS_KEY_ID: "{{ site_backup_s3_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ site_backup_s3_secret }}"
        RESTIC_PASSWORD: "{{ site_backup_password }}"
      register: command_result
      failed_when: "(command_result.stderr | length > 0) and ('config file already exists' not in command_result.stderr)"
      changed_when: false

    - name: "backup site files"
      command: "restic -r {{ site_backup_repo }} --tag {{ site_backup_tag }} --json backup ./"
      environment:
        AWS_ACCESS_KEY_ID: "{{ site_backup_s3_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ site_backup_s3_secret }}"
        RESTIC_PASSWORD: "{{ site_backup_password }}"
      args:
        chdir: "{{ backup_path }}"
      changed_when: false
      register: result

    - name: "result"
      debug:
        msg: "{{ result.stdout_lines | last }}"
