---
- hosts: "{{ host }}"
  roles:
    - role: "../../roles/php"
    - role: "../../roles/nginx"
  tasks:
    - assert:
        that:
          - php_version is defined
          - site_name is defined

    - name: "destroy nginx configs"
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/opt/sitepilot/sites/{{ site_name }}"
        - "/etc/nginx/sites-enabled/{{ site_name }}"
        - "/etc/nginx/sites-available/{{ site_name }}"
      notify:
        - reload nginx

    - name: cleanup fpm pools
      include_tasks: includes/cleanup-pool.yml
      vars:
        destroy: true
      loop: "{{ php_versions }}"

    - meta: flush_handlers

    - name: "destroy site user"
      user:
        name: "{{ site_name }}"
        state: absent
