---
- hosts: "{{ host }}"
  vars:
    site_ssh_enabled: false
    site_xmlrpc_protection_enabled: false
    site_uploads_protection_enabled: false
    site_authorized_keys: []
    site_user_groups:
      - site-users
  roles:
    - role: "../../roles/php"
    - role: "../../roles/nginx"
  tasks:
    - assert:
        that:
          - php_version is defined
          - site_name is defined
          - site_domains is defined
          - site_password is defined
      tags: ["user"]

    - set_fact:
        site_user_groups: "{{ site_user_groups }} + [ 'sftp-only' ]"
      when: not site_ssh_enabled
      tags: ["user"]

    - name: "create site user"
      user:
        name: "{{ site_name }}"
        password: "{{ site_password }}"
        groups: "{{ site_user_groups }}"
        shell: /bin/jailshell
        append: false
        create_home: true
        home: /opt/sitepilot/sites/{{ site_name }}/home
      tags: ["user"]

    - name: "add authorized keys"
      authorized_key:
        user: "{{ site_name }}"
        state: "present"
        key: "{{ site_authorized_keys | join('\n') }}"
        exclusive: true
      tags: ["user"]

    - name: "create site folders"
      file:
        path: "{{ item.path }}"
        mode: "0755"
        state: directory
        owner: "{{ item.user }}"
        group: "{{ item.user }}"
      loop:
        - path: "/opt/sitepilot/sites/{{ site_name }}"
          user: root
        - path: "/opt/sitepilot/sites/{{ site_name }}/logs"
          user: root
        - path: "/opt/sitepilot/sites/{{ site_name }}/files"
          user: "{{ site_name }}"
        - path: "/opt/sitepilot/sites/{{ site_name }}/home/.local/bin"
          user: "{{ site_name }}"

    - name: "create symlinks"
      file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
        mode: "0755"
      loop:
        - src: "/opt/sitepilot/sites/{{ site_name }}/files"
          dest: "/opt/sitepilot/sites/{{ site_name }}/home/files"
        - src: "/opt/sitepilot/sites/{{ site_name }}/logs"
          dest: "/opt/sitepilot/sites/{{ site_name }}/home/logs"
        - src: "/usr/bin/php{{ php_version }}"
          dest: "/opt/sitepilot/sites/{{ site_name }}/home/.local/bin/php"

    - name: "setup acl"
      acl:
        path: "{{ item.path }}"
        entity: "{{ item.entity }}"
        etype: "{{ item.etype }}"
        permissions: "{{ item.permissions }}"
        state: present
        default: "{{ item.default }}"
      loop:
        - path: "/opt/sitepilot/sites/{{ site_name }}"
          permissions: rx
          entity: "{{ site_name }}"
          etype: "user"
          default: false
        - path: "/opt/sitepilot/sites/{{ site_name }}/files"
          permissions: rwx
          entity: "{{ site_name }}"
          etype: "user"
          default: true
        - path: "/opt/sitepilot/sites/{{ site_name }}/files"
          permissions: rwx
          entity: "site-admins"
          etype: "group"
          default: false
        - path: "/opt/sitepilot/sites/{{ site_name }}/files"
          permissions: rwx
          entity: "site-admins"
          etype: "group"
          default: true
        - path: "/opt/sitepilot/sites/{{ site_name }}"
          permissions: ---
          entity: "site-users"
          etype: "group"
          default: false

    - name: "copy shared files"
      copy:
        src: "files/share"
        dest: /opt/sitepilot/sites
        owner: www-data
        group: www-data
        mode: "0755"

    - name: "generate jailshell script"
      template:
        src: templates/jailshell.j2
        dest: "/bin/jailshell"
        mode: "0755"

    - name: "configure nginx"
      template:
        src: templates/nginx.j2
        dest: "/etc/nginx/sites-available/{{ site_name }}"
        mode: "0644"
      notify: reload nginx

    - name: "configure pool"
      template:
        src: templates/pool.j2
        dest: "/etc/php/{{ php_version }}/fpm/pool.d/{{ site_name }}.conf"
        mode: "0644"
      notify: "reload php{{ php_version }}-fpm"

    - name: "enable site"
      file:
        src: "/etc/nginx/sites-available/{{ site_name }}"
        dest: "/etc/nginx/sites-enabled/{{ site_name }}"
        state: link
        mode: "0644"
      notify: reload nginx

    - name: cleanup fpm pools
      include_tasks: includes/cleanup-pool.yml
      loop: "{{ php_versions }}"
