---
- hosts: "{{ host }}"
  vars:
    site_ssh_enabled: false
    site_cache_enabled: false
    site_security_enabled: true
    site_open_basedir_enabled: false
    site_authorized_keys: []
    site_user_groups:
      - site-users
    site_htpasswd: ""
  roles:
    - role: "../../roles/php"
      tags: ["php"]
      vars:
        php_version: "{{ site_php_version }}"
    - role: "../../roles/openresty"
      tags: ["openresty"]
  tasks:
    - assert:
        that:
          - site_name is defined
          - site_domains is defined
          - site_password is defined
          - site_php_version is defined

    - set_fact:
        site_user_groups: "{{ site_user_groups }} + [ 'sftp-only' ]"
      when: not site_ssh_enabled

    - name: "create site user"
      user:
        name: "{{ site_name }}"
        password: "{{ site_password }}"
        groups: "{{ site_user_groups }}"
        shell: /bin/jailshell
        append: false
        create_home: true
        home: /opt/sitepilot/sites/{{ site_name }}/home

    - name: "add authorized keys"
      authorized_key:
        user: "{{ site_name }}"
        state: "present"
        key: "{{ site_authorized_keys | join('\n') }}"
        exclusive: true

    - name: "create site folders"
      file:
        path: "{{ item.path }}"
        mode: "{{ item.mode }}"
        state: directory
        owner: "{{ item.user }}"
        group: "{{ item.group }}"
      loop:
        - path: "/opt/sitepilot/sites/{{ site_name }}"
          user: root
          group: root
          mode: "0755"
        - path: "/opt/sitepilot/sites/{{ site_name }}/logs"
          user: root
          group: root
          mode: "0755"
        - path: "/opt/sitepilot/sites/{{ site_name }}/.config"
          user: www-data
          group: root
          mode: "0700"
        - path: "/opt/sitepilot/sites/{{ site_name }}/files"
          user: "{{ site_name }}"
          group: "{{ site_name }}"
          mode: "0755"
        - path: "/opt/sitepilot/sites/{{ site_name }}/home/.local/bin"
          user: "{{ site_name }}"
          group: "{{ site_name }}"
          mode: "0755"

    - name: "create symlinks"
      file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
        mode: "0755"
      loop:
        - src: "/opt/sitepilot/sites/{{ site_name }}/files"
          dest: "/opt/sitepilot/sites/{{ site_name }}/home/files"
        - src: "/opt/sitepilot/sites/{{ site_name }}/logs"
          dest: "/opt/sitepilot/sites/{{ site_name }}/home/logs"
        - src: "/usr/bin/php{{ site_php_version }}"
          dest: "/opt/sitepilot/sites/{{ site_name }}/home/.local/bin/php"

    - name: "setup acl"
      acl:
        path: "{{ item.path }}"
        entity: "{{ item.entity }}"
        etype: "{{ item.etype }}"
        permissions: "{{ item.permissions }}"
        state: present
        default: "{{ item.default }}"
      loop:
        - path: "/opt/sitepilot/sites/{{ site_name }}"
          permissions: rx
          entity: "{{ site_name }}"
          etype: "user"
          default: false
        - path: "/opt/sitepilot/sites/{{ site_name }}/files"
          permissions: rwx
          entity: "{{ site_name }}"
          etype: "user"
          default: true
        - path: "/opt/sitepilot/sites/{{ site_name }}/files"
          permissions: rwx
          entity: "site-admins"
          etype: "group"
          default: false
        - path: "/opt/sitepilot/sites/{{ site_name }}/files"
          permissions: rwx
          entity: "site-admins"
          etype: "group"
          default: true
        - path: "/opt/sitepilot/sites/{{ site_name }}"
          permissions: ---
          entity: "site-users"
          etype: "group"
          default: false

    - name: "generate jailshell script"
      template:
        src: templates/jailshell.j2
        dest: "/bin/jailshell"
        mode: "0755"

    - name: "generate config files"
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "0644"
      loop:
        - src: "templates/vhost.j2"
          dest: "/opt/sitepilot/sites/{{ site_name }}/.config/vhost.conf"
        - src: "templates/pool.j2"
          dest: "/opt/sitepilot/sites/{{ site_name }}/.config/pool.conf"
        - src: "templates/htpasswd.j2"
          dest: "/opt/sitepilot/sites/{{ site_name }}/.config/htpasswd"
      notify:
        - "reload openresty"
        - "reload php{{ site_php_version }}-fpm"

    - name: "enable site"
      file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
        mode: "0644"
      notify: reload openresty
      loop:
        - src: "/opt/sitepilot/sites/{{ site_name }}/.config/vhost.conf"
          dest: "/usr/local/openresty/nginx/conf/sites-enabled/{{ site_name }}"
        - src: "/opt/sitepilot/sites/{{ site_name }}/.config/pool.conf"
          dest: "/etc/php/{{ site_php_version }}/fpm/pool.d/{{ site_name }}.conf"

    - name: cleanup fpm pools
      include_tasks: includes/cleanup-pool.yml
      loop: "{{ php_versions }}"
