---
- package_facts:
    manager: "auto"

- assert:
    that:
      - node_exporter_version | string | length > 0
      - "'openlitespeed' in ansible_facts.packages"

- set_fact:
    node_exporter_release_name: "node_exporter-{{ node_exporter_version }}.linux-amd64"

- name: check if installer exists
  stat:
    path: /opt/sitepilot/stack/node-exporter/{{ node_exporter_version }}.tar.gz
  register: installer

- name: "create folders"
  file:
    path: "{{ item }}"
    state: directory
    owner: "root"
    group: "root"
    mode: "0700"
  loop:
    - "/opt/sitepilot/stack/node-exporter"
    - "/opt/sitepilot/stack/node-exporter/bin"

- name: "download node exporter binary"
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/{{ node_exporter_release_name }}.tar.gz"
    dest: "/opt/sitepilot/stack/node-exporter/{{ node_exporter_version }}.tar.gz"
  notify: restart node-exporter
  when: not installer.stat.exists

- name: "unarchive node exporter binary"
  unarchive:
    copy: false
    src: "/opt/sitepilot/stack/node-exporter/{{ node_exporter_version }}.tar.gz"
    dest: "/tmp"
    creates: "/tmp/{{ node_exporter_release_name }}/node_exporter"
  notify: restart node-exporter
  when: not installer.stat.exists

- name: "move binary to stack folder"
  command: mv /tmp/{{ node_exporter_release_name }}/node_exporter /opt/sitepilot/stack/node-exporter/bin
  changed_when: false
  when: not installer.stat.exists

- name: "generate service configuration"
  template:
    src: service.j2
    dest: /etc/systemd/system/node-exporter.service
    mode: "0644"
  notify: restart node-exporter

- name: "enable on startup"
  systemd:
    name: node-exporter
    daemon_reload: true
    enabled: true

- name: "cleanup extracted files"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/{{ node_exporter_release_name }}
