---
- package_facts:
    manager: "auto"

- assert:
    that:
      - mailhog_version | string | length > 0
      - docker_network_name | length > 0
      - "'{{ mailhog_version }}' in mailhog_versions"
      - "'openlitespeed' in ansible_facts.packages"
      - "'docker-ce' in ansible_facts.packages"

- name: "start container"
  docker_container:
    name: "mailhog"
    hostname: "mailhog"
    image: "mailhog/mailhog:{{ mailhog_version }}"
    pull: true
    restart_policy: always
    ports:
      - "127.0.0.1:8002:8025"
      - "127.0.0.1:1025:1025"
    env:
      MH_UI_WEB_PATH: "/-/mailhog"
    networks:
      - name: "{{ docker_network_name }}"
    purge_networks: true
    networks_cli_compatible: false
