---
- name: reload php7.4-fpm
  service:
    name: "php7.4-fpm"
    state: reloaded

- name: reload php8.0-fpm
  service:
    name: "php8.0-fpm"
    state: reloaded

- name: reload php8.1-fpm
  service:
    name: "php8.1-fpm"
    state: reloaded
